# Generated by Django 2.2.1 on 2019-05-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hust_library', '0002_auto_20190529_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='administrator',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='administrator',
        ),
    ]
