# Generated by Django 2.2.1 on 2019-06-01 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hust_library', '0003_auto_20190529_2052'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('name', 'publish', 'time', 'price')},
        ),
    ]
