# Generated by Django 2.2.1 on 2019-06-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hust_library', '0004_auto_20190601_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='write',
            name='writer',
            field=models.CharField(max_length=150),
        ),
    ]
